// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnIkdSq76FjoxONSf_dx_Ty_vJtzU3tUE',
    appId: '1:207851962639:web:a6008a2d878d26b069fe7a',
    messagingSenderId: '207851962639',
    projectId: 'login-a71ef',
    authDomain: 'login-a71ef.firebaseapp.com',
    databaseURL: 'https://login-a71ef-default-rtdb.firebaseio.com',
    storageBucket: 'login-a71ef.firebasestorage.app',
    measurementId: 'G-BQYWQG9VBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNd5DaM-wSsuQSqeGYXFLQTrLCySbGvPg',
    appId: '1:207851962639:android:4de2f8a10ddc1ced69fe7a',
    messagingSenderId: '207851962639',
    projectId: 'login-a71ef',
    databaseURL: 'https://login-a71ef-default-rtdb.firebaseio.com',
    storageBucket: 'login-a71ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkqHajNzHzCGFakH_GETrrfpZ7a_eErMU',
    appId: '1:207851962639:ios:7166484de838e41f69fe7a',
    messagingSenderId: '207851962639',
    projectId: 'login-a71ef',
    databaseURL: 'https://login-a71ef-default-rtdb.firebaseio.com',
    storageBucket: 'login-a71ef.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkqHajNzHzCGFakH_GETrrfpZ7a_eErMU',
    appId: '1:207851962639:ios:7166484de838e41f69fe7a',
    messagingSenderId: '207851962639',
    projectId: 'login-a71ef',
    databaseURL: 'https://login-a71ef-default-rtdb.firebaseio.com',
    storageBucket: 'login-a71ef.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnIkdSq76FjoxONSf_dx_Ty_vJtzU3tUE',
    appId: '1:207851962639:web:21ae04ae0142878969fe7a',
    messagingSenderId: '207851962639',
    projectId: 'login-a71ef',
    authDomain: 'login-a71ef.firebaseapp.com',
    databaseURL: 'https://login-a71ef-default-rtdb.firebaseio.com',
    storageBucket: 'login-a71ef.firebasestorage.app',
    measurementId: 'G-MHYKZ2TRTG',
  );
}
